"""Add the durable simulated operation queue and internal probe requests."""

import sqlalchemy as sa
from alembic import op

revision = "007_durable_operations"
down_revision = "006_environment_bindings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("binding_id", sa.Uuid(), nullable=False),
        sa.Column("binding_version", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("execution_mode", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=36), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("diagnostic_code", sa.String(length=50), nullable=True),
        sa.Column("retry_of", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind = 'queue_probe' AND execution_mode = 'simulated'",
            name="ck_operation_handler",
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','retry_wait','reconciling','succeeded','failed','cancelled','needs_attention')",
            name="ck_operation_status",
        ),
        sa.CheckConstraint(
            "fencing_token >= 0 AND attempt_count >= 0 AND max_attempts BETWEEN 1 AND 3",
            name="ck_operation_counters",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["environment_bindings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retry_of"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operations_application_id"),
        "operations",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "ix_operations_queue", "operations", ["status", "available_at"], unique=False
    )
    op.create_table(
        "operation_attempts",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=36), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("diagnostic_code", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("phase IN ('execute','reconcile')", name="ck_attempt_phase"),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id", "fencing_token", name="uq_attempt_fence"),
    )
    op.create_index(
        op.f("ix_operation_attempts_operation_id"),
        "operation_attempts",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "operation_reservations",
        sa.Column("binding_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["environment_bindings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("operation_id"),
    )
    op.create_table(
        "queue_probes",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id"),
    )
    op.create_table(
        "operation_commands",
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_id", "action", "target_id", "key", name="uq_operation_command"
        ),
    )
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=36), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("worker_heartbeats")
    op.drop_table("operation_commands")
    op.drop_table("queue_probes")
    op.drop_table("operation_reservations")
    op.drop_table("operation_attempts")
    op.drop_table("operations")
