"""Add immutable local preparation records; preserve migrations 001–007."""

import json

import sqlalchemy as sa
from alembic import op

revision = "008_prepared_revisions"
down_revision = "007_durable_operations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_versions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("parameter_schema", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artifacts",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.CheckConstraint("size >= 0 AND size <= 2000000", name="ck_artifact_size"),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "generations",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.String(length=80), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("binding_snapshot", sa.JSON(), nullable=False),
        sa.Column("artifact_digest", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artifact_digest"],
            ["artifacts.digest"],
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id"),
    )
    op.create_index(
        op.f("ix_generations_application_id"),
        "generations",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "deployment_revisions",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("source_kind", sa.String(length=30), nullable=False),
        sa.Column("artifact_digest", sa.String(length=64), nullable=False),
        sa.Column("template_id", sa.String(length=80), nullable=False),
        sa.Column("template_digest", sa.String(length=64), nullable=False),
        sa.Column("binding_id", sa.Uuid(), nullable=False),
        sa.Column("binding_snapshot", sa.JSON(), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("config_digest", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artifact_digest"],
            ["artifacts.digest"],
        ),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["environment_bindings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["generations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_revisions_application_id"),
        "deployment_revisions",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "validation_results",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("validator_version", sa.String(length=50), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("report_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scope = 'offline' AND result IN ('passed','failed')",
            name="ck_validation_scope_result",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_digest"],
            ["artifacts.digest"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["deployment_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id"),
    )
    op.create_index(
        op.f("ix_validation_results_revision_id"),
        "validation_results",
        ["revision_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.drop_constraint("ck_operation_handler", "operations", type_="check")
    op.create_check_constraint(
        "ck_operation_handler",
        "operations",
        "(kind = 'queue_probe' AND execution_mode = 'simulated') OR (kind IN ('generate_bundle','validate_offline') AND execution_mode = 'offline')",
    )
    table = sa.table(
        "template_versions",
        sa.column("id", sa.String),
        sa.column("content_digest", sa.String),
        sa.column("parameter_schema", sa.JSON),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        table,
        [
            {
                "id": "python-batch:1.0.0",
                "content_digest": "cf2b1c8ebe8e7da6f456a729ffb2157094c8ddfa3bc578fb43ee0bd62d21276e",
                "parameter_schema": op.inline_literal(
                    json.dumps(
                        {
                            "additionalProperties": False,
                            "properties": {
                                "package_name": {
                                    "default": "batch_app",
                                    "maxLength": 46,
                                    "pattern": "^batch_[a-z][a-z0-9_]{0,39}$",
                                    "title": "Package Name",
                                    "type": "string",
                                }
                            },
                            "title": "TemplateParameters",
                            "type": "object",
                        }
                    )
                ),
                "active": True,
            }
        ],
        multiinsert=False,
    )
    op.execute("""CREATE FUNCTION reject_preparation_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
        RAISE EXCEPTION 'Preparation record is immutable'; END; $$""")
    for table_name in ("artifacts", "deployment_revisions", "validation_results"):
        op.execute(
            f"CREATE TRIGGER immutable_preparation BEFORE UPDATE OR DELETE ON {table_name} FOR EACH ROW EXECUTE FUNCTION reject_preparation_mutation()"
        )
    op.execute(
        "CREATE TRIGGER immutable_template BEFORE UPDATE OF id, content_digest, parameter_schema OR DELETE ON template_versions FOR EACH ROW EXECUTE FUNCTION reject_preparation_mutation()"
    )


def downgrade() -> None:
    # A database containing preparation history must be retained, not downgraded.
    bind = op.get_bind()
    if bind.scalar(
        sa.text("SELECT EXISTS(SELECT 1 FROM operations WHERE kind <> 'queue_probe')")
    ):
        raise RuntimeError("Cannot downgrade a database with preparation history")
    for table_name in (
        "validation_results",
        "deployment_revisions",
        "generations",
        "artifacts",
        "template_versions",
    ):
        op.drop_table(table_name)
    op.execute("DROP FUNCTION reject_preparation_mutation()")
    op.drop_constraint("ck_operation_handler", "operations", type_="check")
    op.create_check_constraint(
        "ck_operation_handler",
        "operations",
        "kind = 'queue_probe' AND execution_mode = 'simulated'",
    )
